/**
 * test.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TestResponse from './TestResponse';

/**
 * The TestEchoResp model module.
 * @module model/TestEchoResp
 * @version version not set
 */
class TestEchoResp {
    /**
     * Constructs a new <code>TestEchoResp</code>.
     * @alias module:model/TestEchoResp
     */
    constructor() { 
        
        TestEchoResp.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TestEchoResp</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TestEchoResp} obj Optional instance to populate.
     * @return {module:model/TestEchoResp} The populated <code>TestEchoResp</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TestEchoResp();

            if (data.hasOwnProperty('Response')) {
                obj['Response'] = TestResponse.constructFromObject(data['Response']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/TestResponse} Response
 */
TestEchoResp.prototype['Response'] = undefined;






export default TestEchoResp;

