/**
 * test.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TestError model module.
 * @module model/TestError
 * @version version not set
 */
class TestError {
    /**
     * Constructs a new <code>TestError</code>.
     * @alias module:model/TestError
     */
    constructor() { 
        
        TestError.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TestError</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TestError} obj Optional instance to populate.
     * @return {module:model/TestError} The populated <code>TestError</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TestError();

            if (data.hasOwnProperty('Code')) {
                obj['Code'] = ApiClient.convertToType(data['Code'], 'String');
            }
            if (data.hasOwnProperty('Message')) {
                obj['Message'] = ApiClient.convertToType(data['Message'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} Code
 */
TestError.prototype['Code'] = undefined;

/**
 * @member {String} Message
 */
TestError.prototype['Message'] = undefined;






export default TestError;

