/**
 * test.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TestError from './TestError';

/**
 * The TestResponse model module.
 * @module model/TestResponse
 * @version version not set
 */
class TestResponse {
    /**
     * Constructs a new <code>TestResponse</code>.
     * @alias module:model/TestResponse
     */
    constructor() { 
        
        TestResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TestResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TestResponse} obj Optional instance to populate.
     * @return {module:model/TestResponse} The populated <code>TestResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TestResponse();

            if (data.hasOwnProperty('Error')) {
                obj['Error'] = TestError.constructFromObject(data['Error']);
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/TestError} Error
 */
TestResponse.prototype['Error'] = undefined;

/**
 * @member {String} value
 */
TestResponse.prototype['value'] = undefined;






export default TestResponse;

