/**
 * test.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ProtobufAny from './model/ProtobufAny';
import RpcStatus from './model/RpcStatus';
import TestEchoResp from './model/TestEchoResp';
import TestError from './model/TestError';
import TestRequestBody from './model/TestRequestBody';
import TestResponse from './model/TestResponse';
import TestApi from './api/TestApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var TestProto = require('index'); // See note below*.
* var xxxSvc = new TestProto.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new TestProto.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new TestProto.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new TestProto.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version version not set
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ProtobufAny model constructor.
     * @property {module:model/ProtobufAny}
     */
    ProtobufAny,

    /**
     * The RpcStatus model constructor.
     * @property {module:model/RpcStatus}
     */
    RpcStatus,

    /**
     * The TestEchoResp model constructor.
     * @property {module:model/TestEchoResp}
     */
    TestEchoResp,

    /**
     * The TestError model constructor.
     * @property {module:model/TestError}
     */
    TestError,

    /**
     * The TestRequestBody model constructor.
     * @property {module:model/TestRequestBody}
     */
    TestRequestBody,

    /**
     * The TestResponse model constructor.
     * @property {module:model/TestResponse}
     */
    TestResponse,

    /**
    * The TestApi service constructor.
    * @property {module:api/TestApi}
    */
    TestApi
};
